version: '3.7'

services:
  postgres:
    image: postgres # https://hub.docker.com/_/postgres
    container_name: expressauth_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - database-network

  adminer:
    image: adminer # https://hub.docker.com/_/adminer
    container_name: expressauth_adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
